#!/usr/bin/env bash 

set -o vi

export HISTCONTROL=ignoredups:erasedups
shopt -s histappend

export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"

export PATH="$PATH:$HOME/bin"

source ~/.aliases

export SBT_OPTS="-Xms512m -Xmx2048m -XX:ReservedCodeCacheSize=256m -XX:MaxMetaspaceSize=512m"

alias ls='ls -G'

# assumes bash-completion is installed `brew install git bash-completion`
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

PS1="\[\033[32m\]\w\[\033[0m\]\$(__git_ps1)\n\[\033[1;36m\]\u\[\033[32m\]$ \[\033[0m\]"

export LESS=-RFX
