#!/usr/bin/env bash 

set -o vi

export HISTCONTROL=ignoredups:erasedups
shopt -s histappend

export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

source ~/.aliases

export SBT_OPTS="-Xms2048m -Xmx2048m -XX:ReservedCodeCacheSize=256m -XX:MaxMetaspaceSize=512m"

source /Users/loaner/.hp_devtools/autocomplete.sh

alias ls='ls -G'

