#!/usr/bin/env bash 

set -o vi

export HISTCONTROL=ignoredups:erasedups
shopt -s histappend

export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}"
#history -a; history -c; history -r"

export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"

export PATH="$PATH:$HOME/bin"

source ~/.aliases

export SBT_OPTS="-Xms512m -Xmx2048m -XX:ReservedCodeCacheSize=256m -XX:MaxMetaspaceSize=512m"

alias ls='ls -G'
alias l="ls"

# assumes bash-completion is installed `brew install git bash-completion`
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

PS1="\[\033[32m\]\w\[\033[0m\]\$(__git_ps1)\n\[\033[1;36m\]\u\[\033[32m\]$ \[\033[0m\]"

export LESS=-RFX

ulimit -n 8192

export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=$HOME/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

export ANDROID_HOME=/usr/local/opt/android-sdk
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

# run before chrome dev
#export PATH=$PATH:$HOME/dev/depot_tools

