syntax enable     " enable syntax processing
set tabstop=2     " number of visual spaces per TAB
set softtabstop=2 " number of spaces in tab when editing
set shiftwidth=2  " indentation
set expandtab     " tabs are spaces
set number        " show line numbers
set showcmd       " show command in bottom bar
set cursorline    " highlight current line

set wildmode=longest,list,full " show autocomplete
set wildmenu " visual autocomplete for commands

set lazyredraw " redraw only when we necessary 

" searching
set ignorecase
set smartcase
set incsearch " search as characters are typed
set hlsearch " highlight search matches

set showmatch           " highlight matching braces

" assumes vundle was cloned locally with `git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim`
set nocompatible              " required by vundle
filetype off                  " required by vundle
set rtp+=~/.vim/bundle/Vundle.vim " set the runtime path to include Vundle and initialize
call vundle#begin()

Plugin 'fatih/vim-go'
Plugin 'derekwyatt/vim-scala'
Plugin 'gmarik/Vundle.vim' " let Vundle manage Vundle, required

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required


