#!/usr/bin/perl

chomp(@p = (@f = ($" x 80) x 24, <ARGV>)[-24..-1]);
{
  @s = (join('', map((rand > 0.1 ? $" : '*'), 1..80)), @s);
  if (@s > 23) {
    foreach (0 .. 23) {
      $t = $f[$_];
      print( $_ ? $/ : "\e[H" );
      print( ($f[$_] |= $s[$_] & $p[$_]) | ($s[$_] &= ~$t ^ $f[$_]) );
    }
    select '', '', '', 0.1;
  }
  redo;
}
